# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78b6be9ded8a7d86522668040dcd67c423a7cf7337d8f8e2e96e4c65c82bf55c0126d15f3ed3986a72cea3dff33bdc3fd4adbfa81b2bbd14c861a7a7361f8b25

test:
  secret_key_base: 12f4e6d39824106e29f050d73914440fc2d65c5bd1d79f9adb778cb6f2265481652148648bbd252da29c1912a3321633884463a484da6b56a7d250c118f98bee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
